In [1]:
import numpy as np

In [18]:
l=[1,2,3,4]

In [19]:
a=np.array(l)

In [20]:
type(a)

numpy.ndarray

In [22]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [8]:
b=np.array([[1,2],[3,4]])

In [9]:
type(b)

numpy.ndarray

In [10]:
np.asanyarray(b)

array([[1, 2],
       [3, 4]])

In [11]:
np.asarray(b)

array([[1, 2],
       [3, 4]])

In [15]:
np.array(b)

array([[1, 2],
       [3, 4]])

In [ ]:
# array super class and matrix subset of array and subclaas

In [ ]:
#matrix by default two deminisional

In [12]:
c=np.matrix(l)

In [13]:
c

matrix([[1, 2, 3, 4]])

In [14]:
type(c)

numpy.matrix

In [30]:
# solo copy use  and reference change as location 

In [31]:
a=np.array(l)

In [32]:
a

array([1, 2, 3, 4])

In [33]:
c=a

In [34]:
c[0]

1

In [35]:
c[0]=100

In [36]:
c

array([100,   2,   3,   4])

In [29]:
a

array([100,   2,   3,   4])

In [53]:
# dep copy

In [54]:
d=np.copy(a)

In [55]:
d

array([100,   2,   3,   4])

In [61]:
a

array([100,   2,   3,   4])

In [62]:
d[2]

200

In [63]:
d[2]=200

In [64]:
d

array([100,   2, 200,   4])

In [66]:
np.fromfunction(lambda i,j :i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [70]:
np.fromfunction(lambda i,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [74]:
iterable=(i*i for i in range(5))

In [75]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [79]:
np.fromstring('323 323 2',sep=' ')

array([323., 323.,   2.])

In [81]:
np.fromstring('4,3',sep=",")

array([4., 3.])

In [82]:
#numpy data types

In [83]:
l=[1,3,4,5,6]

In [84]:
ar=np.array(l)

In [85]:
type(ar)

numpy.ndarray

In [ ]:
ar.ndim